
apiVersion: v1
kind: Namespace
metadata:
  name: dashy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dashy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/app/public/conf.yml"
              subPath: "conf.yml"
              readOnly: true
      volumes:
      - name: config
        secret:
          secretName: dashy
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: dashy
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
  namespace: dashy
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
      - dash.absurdlab.elan-vision.com
    secretName: dashy-tls
  rules:
  - host: "dash.absurdlab.elan-vision.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dashy
            port:
              name: http