apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dashy
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./proxmox/k3s/dashy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
