apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aliyun
  namespace: cert-manager
spec:
  encryptedData:
    access-key: AgALTlMq82Tn55Dxx09+JAEbOV5CvORhE89cutye+dBiM3hIj8TTSzZAjX0TQKUiZRDtll/WlY1+lMLHWiUa5ZOQT2QRinEo+tOINLUiXxn2LCUQb2yDaZ21oC6KzFAEES8iFocw6oLcQFBTohmGhu/89kKCV2kW9rZMdJe7uXnCl0Z0XHYrjw6lyf3Rtft0xhQQiinAXjawx1g/WHAF4ZVgPLVFUesUo1Log1qH2qN4+P2x0IB/fXmne229XPeZuKTtx+kxFgYjuDABKp6j8HCAWZlojpUpKRX+tONsM4hrz85cYCxLNiPO8MpjUBBry85qihbb069azSrC62ShF3FdeAghet/u5i+m/5uyT8rlw+hhQWr51DXXLdK/HTLtetHDh8r8cbFljvVqZuoQNnFUhF5FisZfcJhplmUFdtby9lzUwApRkqx5rlwCS+xRTSoC8K5whAMtV0tW7Yoyx+xyhWEXcxZbcg26/2+Z6aDTuLTO/6ru5fnPwjBFE6tnaUbUYiZV+qqe/a/weUq3cy1Qsv8V+0y78YsZJ6tlhKQPG4PAxj35SRrY+JFCYLgmSFICBz1w19XyfBBT3wFdahs75ridxouDTPVJNfRr8kawXW39s7Ch3MA7aovjapOCVT2SPFOIkx6lb8g7ua2sEXn3JmrCYIAemuKjYr5iI/ZCf0hf0BdWPkeO+555C8wOutVX+RoqSinJQenpNJau8sz1mkl+lDTip8c=
    secret-key: AgCpKahPjNrmFRGjx4C3VctInzPx1XlWjT9khtzh5gYCE3pBDaN0PN0zrd+YWQ91q8ZVho40xmtfzDM4Qh2R64TqAq4YY83HEmIzI4TvblywkoA/DuayS3I80LNrcfFuHyVfYEqeuX4ysdMbvCbmcgu51x5AziGQWvf0jrjSiW5OwPMdea734Qceg4brZCEJ1ieP0IelySHPYhTqN29H2KsgI28p4m+iywgOT2+N/RbtKIf/KxJsfwmSxq9OUEmY9VTcTaaz6etv336vKU3rKdSo72GKgERCVhE19MOXyFPiyYjOVmPUfTncyyYIgOQ27KrruKahU1ZQgtrhiZGluJiv/1q5lnOWhteCKiJvDYGBGUDjwRz1JXHKmOLEpGCAttHg08DHTxpDzFZfF1uSM3XAyDcONmfqL1j9Z0LYT3i+ueTISS1VzpD13kPuIeot0m/A3OSCB5F4336Yp2Ly2kNNe2UbjqXqZqEKsYtNKmF4UD8aGcv/ptBGB+PK/EbTgqvZgM1L5Bvhnh5CZmvA0PZzdI1T4e/HSa9QbFRIm3dSt/4UBKLZT7jktGCyVtbIbAr1JinTDRRGmaPleai7euI6twRv3NknHOAov5iB30+jPKXm7N0OLLP1XrjvMeT3SgMIfQg7uFs6cl8M7yuYzcAzgNTlMInJaDCuftbMMaBqB848O7NLZ/T3AZvgweYXz1oFrgyo+hKEAnH8jUbQXfN25eQL6v4WSm5rKh34OQo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aliyun
      namespace: cert-manager

