
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager-system
spec:
  interval: 24h0m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager-system
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: '>=v1.7.0 <v1.8.0'
  install:
    crds: Create
  interval: 1h0m0s
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    prometheus:
      enabled: false