apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../ingress-nginx-system/sync.yaml
- ../sealed-secrets-system/sync.yaml
- ../cert-manager-system/sync.yaml
