
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: sealed-secrets-system
spec:
  interval: 30s
  path: ./proxmox/k3s/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
