apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./proxmox/k3s/ingress-nginx-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
